#+title: Change Log for bank-Buddy
#+author: James Dyer
#+email: captainflasmr@gmail.com
#+language: en
#+options: ':t toc:nil author:nil email:nil num:nil title:nil
#+todo: TODO DOING | DONE
#+startup: showall

This document contains the release notes for each tagged commit on the
project's main git repository: [[https://github.com/captainflasmr/bank-buddy]]

* Versions

** <2025-05-09> 0.2.1

Improved the readability of the monthly progress comparison by inverting so the graph lines are always going to be clearer.

** <2025-04-26> 0.2.0

Removed all Babel blocks and now generate =gnuplot= data files and images through an external call-process. This means that the user still has the flexibility to modify a =gnuplot= output, but instead of modifying an embedded Babel gnuplot source block and regenerating the data, the files on disk can be modified. As a result, no Babel dependencies need to be installed, and there is no need to confirm a Babel block evaluation on each report load.

** <2025-04-26> 0.1.2

- Added monthly transaction counts

This section shows the number of transactions processed for each month.

** <2025-04-12> 0.1.1

Removed csv package dependency

** <2025-04-09> 0.1.0

Refactor code and improve customization options

- Remove redundant comments and simplify code structure.
- Enhance customization options by adding =defcustom= for user settings.
- Introduce new functions for better code modularity and maintainability.
- Adjust plots and visualization settings for improved clarity.
  
